
IF( NOT WIPP_FOUND )

IF( ${CMAKE_CL_64} )
ELSE( ${CMAKE_CL_64} )
	FILE(GLOB WIPP_INCLUDE_PATHS_0 "$ENV{ProgramFiles(x86)}/Intel/WIPP/*.*/ia32/include")
	FILE(GLOB WIPP_INCLUDE_PATHS_1 "/opt/intel/ipp/*.*/ia32/include")
	FILE(GLOB WIPP_INCLUDE_PATHS_2 "/usr/local/intel/ipp/*.*/ia32/include")
	FILE(GLOB WIPP_LIBRARY_PATHS_0 "$ENV{ProgramFiles(x86)}/Intel/WIPP/*.*/ia32/lib")
	FILE(GLOB WIPP_LIBRARY_PATHS_1 "$ENV{ProgramFiles(x86)}/Intel/WIPP/*.*/ia32/stublib")
	FILE(GLOB WIPP_LIBRARY_PATHS_2 "/opt/intel/ipp/*.*/ia32/lib")
	FILE(GLOB WIPP_LIBRARY_PATHS_3 "/opt/intel/ipp/*.*/ia32/sharedlib")
	FILE(GLOB WIPP_LIBRARY_PATHS_4 "/usr/local/intel/ipp/*.*/ia32/lib")
	FILE(GLOB WIPP_LIBRARY_PATHS_5 "/usr/local/intel/ipp/*.*/ia32/sharedlib")
ENDIF( ${CMAKE_CL_64} )

SET(
	WIPP_INCLUDE_PATHS
	${WIPP_INCLUDE_PATHS_0}
	${WIPP_INCLUDE_PATHS_1}
	${WIPP_INCLUDE_PATHS_2}
)

SET(
	WIPP_LIBRARY_PATHS
	${WIPP_LIBRARY_PATHS_0}
	${WIPP_LIBRARY_PATHS_1}
	${WIPP_LIBRARY_PATHS_2}
	${WIPP_LIBRARY_PATHS_3}
	${WIPP_LIBRARY_PATHS_4}
	${WIPP_LIBRARY_PATHS_5}
)

FIND_PATH(
  WIPP_INCLUDE_DIR
  ippi.h
  ${WIPP_INCLUDE_PATHS}
)

FIND_LIBRARY( WIPP_WIPPCORELMERGED NAMES ippcorel ippcore PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPACEMERGED   NAMES ippacemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPACMERGED    NAMES ippacmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCCEMERGED   NAMES ippccemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCCMERGED    NAMES ippccmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCHEMERGED   NAMES ippchemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCHMERGED    NAMES ippchmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCVEMERGED   NAMES ippcvemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCVMERGED    NAMES ippcvmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPDCEMERGED   NAMES ippdcemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPDCMERGED    NAMES ippdcmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPIEMERGED    NAMES ippiemerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPIMERGED     NAMES ippimerged       PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPJEMERGED    NAMES ippjemerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPJMERGED     NAMES ippjmerged       PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPMEMERGED    NAMES ippmemerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPMMERGED     NAMES ippmmerged       PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSCEMERGED   NAMES ippscemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSCMERGED    NAMES ippscmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSEMERGED    NAMES ippsemerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSMERGED     NAMES ippsmerged       PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSREMERGED   NAMES ippsremerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSRMERGED    NAMES ippsrmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVCEMERGED   NAMES ippvcemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVCMERGED    NAMES ippvcmerged      PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVMEMERGED   NAMES ippvmemerged     PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVMMERGED    NAMES ippvmmerged      PATHS ${WIPP_LIBRARY_PATHS} )

SET(
  WIPP_MERGED_LIBRARIES
  ${WIPP_WIPPACEMERGED}
  ${WIPP_WIPPACMERGED}
  
  ${WIPP_WIPPCVEMERGED}
  ${WIPP_WIPPCVMERGED}
  
  ${WIPP_WIPPMEMERGED}
  ${WIPP_WIPPMMERGED}
  
  ${WIPP_WIPPDCEMERGED}
  ${WIPP_WIPPDCMERGED}
  
  ${WIPP_WIPPVCEMERGED}
  ${WIPP_WIPPVCMERGED}
  
  ${WIPP_WIPPCCEMERGED}
  ${WIPP_WIPPCCMERGED}
  
  ${WIPP_WIPPCHEMERGED}
  ${WIPP_WIPPCHMERGED}
  
  ${WIPP_WIPPVMEMERGED}
  ${WIPP_WIPPVMMERGED}
  
  ${WIPP_WIPPJEMERGED}
  ${WIPP_WIPPJMERGED}
  
  ${WIPP_WIPPSREMERGED}
  ${WIPP_WIPPSRMERGED}
  
  ${WIPP_WIPPSCEMERGED}
  ${WIPP_WIPPSCMERGED}
  
  ${WIPP_WIPPIEMERGED}
  ${WIPP_WIPPIMERGED}
  
  ${WIPP_WIPPSEMERGED} 
  ${WIPP_WIPPSMERGED}
  
  ${WIPP_WIPPCORELMERGED}
)

FIND_LIBRARY( WIPP_WIPPACSHARED    NAMES    ippac   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCCSHARED    NAMES    ippcc   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCHSHARED    NAMES    ippch   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCORELSHARED NAMES    ippcore PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPCVSHARED    NAMES    ippcv   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPDCSHARED    NAMES    ippdc   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPISHARED     NAMES    ippi    PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPJSHARED     NAMES    ippj    PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPMSHARED     NAMES    ippm    PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSSHARED     NAMES    ipps    PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSCSHARED    NAMES    ippsc   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPSRSHARED    NAMES    ippsr   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVCSHARED    NAMES    ippvc   PATHS ${WIPP_LIBRARY_PATHS} )
FIND_LIBRARY( WIPP_WIPPVMSHARED    NAMES    ippvm   PATHS ${WIPP_LIBRARY_PATHS} )

SET(
  WIPP_SHARED_LIBRARIES
  ${WIPP_WIPPACSHARED}
  ${WIPP_WIPPCCSHARED}
  ${WIPP_WIPPCHSHARED}
  ${WIPP_WIPPCORELSHARED}
  ${WIPP_WIPPCVSHARED}
  ${WIPP_WIPPDCSHARED}
  ${WIPP_WIPPISHARED}
  ${WIPP_WIPPJSHARED}
  ${WIPP_WIPPMSHARED}
  ${WIPP_WIPPSSHARED}
  ${WIPP_WIPPSCSHARED}
  ${WIPP_WIPPSRSHARED}
  ${WIPP_WIPPVCSHARED}
  ${WIPP_WIPPVMSHARED}
)

SET( WIPP_FOUND 0 )
IF( EXISTS "${WIPP_INCLUDE_DIR}" )
  SET( WIPP_FOUND 1 )
	ADD_DEFINITIONS( -DHAVE_WIPP )
  INCLUDE_DIRECTORIES(
    ${WIPP_INCLUDE_DIR}
  )
ENDIF( EXISTS "${WIPP_INCLUDE_DIR}" )

ENDIF( NOT WIPP_FOUND )
